# values.yaml

image:
  repository: 544167776152.dkr.ecr.eu-north-1.amazonaws.com/frontend-dev-ecr
  tag: "1.0"
  pullPolicy: IfNotPresent

replicaCount: 2
service:
  type: LoadBalancer
  port: 80
ingress:
  enabled: false # Change to true if you want to configure an Ingress later
