apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend-guardian.fullname" . }}
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: {{ include "frontend-guardian.name" . }}
